### ISSUE TITLE
cannot view Ufixed16 in IJulia & test fails

### ISSUE THREAD

**Issue by Ken-B** [timholy/Images.jl#269]
Viewing an `Ufixed16` image in IJulia fails with:

```
`map1` has no method matching map1(::BitShift{RGB{UfixedBase{Uint8,8}},8}, ::Float64)

 in _map_a! at C:\Users\Ken\.julia\v0.3\Images\src\map.jl:360
 in map! at C:\Users\Ken\.julia\v0.3\Images\src\map.jl:352
 in image2wand at C:\Users\Ken\.julia\v0.3\Images\src\io.jl:307
 in writemime at C:\Users\Ken\.julia\v0.3\Images\src\io.jl:204
 in base64 at base64.jl:125
 in display_dict at C:\Users\Ken\.julia\v0.3\IJulia\src\execute_request.jl:34
```
However, converting it to `Ufixed8` with `convert(Image{RGB{Ufixed8}},img)` will print the image in IJulia.

The tests also fail

```
julia> `Pkg.test("Images")`
INFO: Testing Images
ERROR: test error during map(mapi,c) == convert(Images.ColorTypes.BGRA{Ufixed8},
c) && typeof(map(mapi,c)) == typeof(convert(Images.ColorTypes.BGRA{Ufixed8},c))
type: AlphaColorValue: in C, expected C<:ColorValue{T}, got Type{UfixedBase{Uint
8,8}}
 in anonymous at test.jl:62
 in do_test at test.jl:37
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at client.jl:285
 in _start at client.jl:354
while loading C:\Users\Ken\.julia\v0.3\Images\test\map.jl, in expression startin
g on line 34
while loading C:\Users\Ken\.julia\v0.3\Images\test\runtests.jl, in expression st
arting on line 5

===============================[ ERROR: Images ]================================


failed process: Process(`'C:\CodingProgs\Julia64\Julia-0.3.6\bin/julia' 'C:\User
s\Ken\.julia\v0.3\Images\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================

INFO: No packages to install, update or remove
ERROR: Images had test errors
 in error at error.jl:21 (repeats 2 times)

julia> versioninfo()
Julia Version 0.3.6
Commit 0c24dca (2015-02-17 22:12 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

Let me know what I can do to help.

**Comment by Ken-B** [comment]
to replicate in IJulia, you can run:
```jl
imgfile = "DSC_2205.NEF"
isfile(imgfile) || download("http://www.mannyphoto.com/D700D3/DSC_2205.NEF",joinpath(pwd(),imgfile)) #free sample file
imgfileppm = splitext(imgfile)[1] * ".ppm"
isfile(imgfileppm) || run(`dcraw -v -4 $imgfile`) #-4 for 16bit linear output
isfile(imgfileppm) || error("during dcraw conversion")
```
and then

    img = imread(imgfileppm)

I'm using IPython 3.0, in case that matters.

**Comment by timholy** [comment]
Fixed.

**Comment by Ken-B** [comment]
Now the tests pass, but the original issue is still unresolved. 

Here's [a 16bit DNG file](https://drive.google.com/file/d/0B_p4_Ikh_c7jUFZ5VlZCU3RLdDA/view?usp=sharing) you can use to replicate. Again, it loads fine in a terminal, but in IJulia when it wants to view the image after loading it some conversion fails. 

I wish I could do something to help, but staring at the map code before and now again, I'm afraid I don't understand what's going on exactly. Let me know if I can be of any assistance.

And of course thanks a lot for looking at this.

**Comment by timholy** [comment]
Turns out your problem only happens on large images. If you do
```
imgsm = getindexim(img, 2001:2500, 1001:1400)
```
then `imgsm` displays just fine. It's because large images are 

FYI, the way to debug this (and most other Julia code) is to insert `@show` statements everywhere along the chain that triggers the error. I'm working on it, but I have many threads in play at once.

**Comment by timholy** [comment]
My OS's version of ImageMagick can't handle your "sky" image. Can you convert it to a different format?

**Comment by Ken-B** [comment]
Here's a link to the original raw file (sky.NEF): https://copy.com/ZpWXGUuFkXX0usCO

FYI, I've also had problems on windows with ImageMagick opening 16bit dng files converted with Adobe DNG converter. The only Q16-x64-dll version that seems to work is 6.9.1-0, not earlier or later versions.

**Comment by timholy** [comment]
Fixed.

> FYI, I've also had problems on windows with ImageMagick opening 16bit dng files converted with Adobe DNG converter. The only Q16-x64-dll version that seems to work is 6.9.1-0, not earlier or later versions.

If you don't mind, it certainly wouldn't hurt to report the problems to the ImageMagick developers. In the long run that will help Julia.

**Comment by Ken-B** [comment]
For reference, here's the ImageMagick bug report (yes, it's on a BB forum, that's how they seem to be organized):
http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=27738

**Comment by timholy** [comment]
Thanks!

**Comment by Ken-B** [comment]
Oh, no. Thank *you*!
